### ISSUE TITLE
Add user-info Endpoint

### ISSUE THREAD

**Issue by eiswind** [spring-projects-experimental/spring-authorization-server#150] opened 2020-11-10 16:09 UTC
**Expected Behavior**

When I try to connect a spring webapp via
`
http.authorizeRequests()
                .anyRequest().authenticated()
                .and().oauth2Login();

`
I don't see if there already exists a user-info endpoint. If there already is one, it would be great to see how it can be accessed.
Any hint would be appreciated.

**Comment by jgrandja** [comment] 2020-11-13 13:18
@eiswind OpenID Connect has not been implemented as of yet. Work is starting on it later this month and the UserInfo endpoint is also part of #53. I'll close this as a duplicate of #53.

**Closed by jgrandja** 2020-11-13 13:18 UTC
Labels: type: enhancement

**Comment by eiswind** [comment] 2020-11-13 13:49
Thanks for letting me know. I'll be watching this :)
