### ISSUE TITLE
JWT-based Client Authentication

### ISSUE THREAD

**Issue by TakahikoKawasaki** [spring-projects-experimental/spring-authorization-server#209] opened 2021-02-03 20:28 UTC
JWT-based client authentication methods defined in [RFC 7523](https://tools.ietf.org/html/rfc7523) [Section 2.2](https://tools.ietf.org/html/rfc7523#section-2.2), namely, `client_secret_jwt` and `private_key_jwt`.

Client authentication is required at some endpoints. It is recommended to design and implement an abstraction layer for client authentication from the beginning. `tls_client_auth` and `self_signed_tls_client_auth` mentioned in #101 also should be handled under the abstraction layer.

**Comment by jgrandja** [comment] 2021-02-17 11:43
Closing as duplicate of #59

**Closed by jgrandja** 2021-02-17 11:43 UTC
Labels: type: enhancement
