### ISSUE TITLE
Sample auth server doesn't work

### ISSUE THREAD

**Issue by avpdiver** [spring-projects-experimental/spring-authorization-server#273] opened 2021-04-01 06:51 UTC
Calling /oauth2/authorize doesn't redirect to login page and always fires 401 HTTP error. 
Example of request:
```
http://auth-server:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=openid&state=state&redirect_uri=https://openidconnect.net/callback
```
I've changed the creation of RegisteredClient a little bit to simplify testing:
```
RegisteredClient registeredClient = RegisteredClient.withId(UUID.randomUUID().toString())
				.clientId("messaging-client")
				.clientSecret("secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
				.authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
				.redirectUri("https://openidconnect.net/callback")
				.scope(OidcScopes.OPENID)
				.scope("message.read")
				.scope("message.write")
				.clientSettings(clientSettings -> clientSettings.requireUserConsent(false).requireProofKey(false))
				.build();
```

**Comment by avpdiver** [comment] 2021-04-01 07:15
I run the sample server at http://37.235.203.176:8888/ if someone would like to reproduce the error :)


[Configuration](http://37.235.203.176:8888/.well-known/openid-configuration) and [/oauth2/authorize](http://37.235.203.176:8888/oauth2/authorize?response_type=code&client_id=messaging-client&scope=openid&state=state&redirect_uri=https://openidconnect.net/callback).

**Comment by Kehrlann** [comment] 2021-04-01 15:48
This is a regression in the samples due to 8d57c893fb54525ffcd94ef9574a20b5a7dd066c , which disallows "localhost" has a redirect-uri host.

A proposed solution could be #275

**Comment by avpdiver** [comment] 2021-04-01 16:58
> This is a regression in the samples due to [8d57c89]
I am afraid, it's not. As I mentioned, I changed a redirect URI to "https://openidconnect.net/callback". No loopbacks.
And login page is accessible. There is no need to 'permitAll' it ;)

**Comment by Kehrlann** [comment] 2021-04-01 19:58
Ah my bad, I thought you had tried this change _after_ noticing the samples were broken.

I cannot access your example, it times out:
```console
$ curl -v --max-time 10 37.235.203.176:9000
*   Trying 37.235.203.176...
* TCP_NODELAY set
* Connection timed out after 10003 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 10003 milliseconds
```

For the `.permitAll()`, you are correct, the login page is indeed accessible if you hit `/login` directly ; or try to access an invalid endpoint `/foob/bar`. 

However, when trying to access `/oauth2/authorize?...` as a non-logged in user, we should get a redirect to `/login` but get an `HTTP 401` instead.  Something in the filter chain is broken, I haven't figured out what just yet, I'll look into it tomorrow. `.permitAll()` fixes that particular problem on my setup, you may want to give it a try.

**Comment by avpdiver** [comment] 2021-04-02 05:25
> I cannot access your example, it times out:

Sorry for that. The server is on my personal PC, I turned it off last night. I've run it again.

> For the `.permitAll()`, you are correct, the login page is indeed accessible if you hit `/login` directly ; or try to access an invalid endpoint `/foob/bar`.

Yes, that's the case. Any other pages fire login page, as does /oauth2/authorize with invalid GET-params. 

>  `.permitAll()` fixes that particular problem on my setup, you may want to give it a try.
I have tried, nothing changed.

**Comment by Kehrlann** [comment] 2021-04-02 15:56
Thanks for opening it up. I've looked into it, I don't know why I believed `permitAll()` changed anything. It doesn't. My bad.

The problem is linked to 85d6a1200021ceb10b41c2e708d036b7cfd7b97a . **tl;dr** do not use that commit until we fix it, I have to check with Joe what would the best approach be.

---

Longer explanation:

The sample relies on `OAuth2AuthorizationServerConfiguration` to build a filter chain for auth-server related endpoints. This chain now throws `401` for any unauthenticated request at the `ExceptionTranslationFilter` level , because of the changes in 85d6a1200021ceb10b41c2e708d036b7cfd7b97a -> the default "redirect to log in page" behavior is not present anymore, because the log-in page must be configured by the application, not `spring-auth-server`. 

Unfortunately, there are two separate filter chains (one for spring-authorization-server, one for OAuth2AuthorizationServerApplication), so I have trouble understanding how we should do this instead.

Note that if you log in _first_ and then visit `/oauth2/authorize?...`, it works.

**Comment by Kehrlann** [comment] 2021-04-02 17:59
For info I have an open PR, #275 , but it's not in a good place yet.

**Comment by jgrandja** [comment] 2021-04-05 20:19
@avpdiver @Kehrlann This is now fixed via 2d8d568

**Closed by jgrandja** 2021-04-05 20:19 UTC
Labels: type: bug

**Comment by igloo12** [comment] 2021-09-28 15:26
I am running to this same problem on the 0.2.0 release

**Comment by sjohnr** [comment] 2021-10-08 17:48
@igloo12, the [sample in this repo](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/boot/oauth2-integration/authorizationserver/src/main/java/sample/config/AuthorizationServerConfig.java#L62) works, so make sure you're configured similarly. Also, make sure your `redirect_uri` is configured with `127.0.0.1` and not `localhost`, like [this sample](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/boot/oauth2-integration/client/src/main/resources/application.yml#L24).

You can also check out the [spring-security samples project](https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/oauth2/authorization-server/) which uses the latest maven dependency.

One note, make sure you are navigating to `http://127.0.0.1:8080` or similar on your client. If you start at `http://localhost:8080` and get redirected to `http://auth-server:9000/oauth2/authorize` you will receive an error. The [oauth2-login sample](https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/oauth2/login/src/main/java/example/filter/LoopbackIpRedirectFilter.java#L62) shows a workaround for this.
