### ISSUE TITLE
JdbcOAuth2AuthorizationService should not use Blob

### ISSUE THREAD

**Issue by clgraf** [spring-projects-experimental/spring-authorization-server#387] opened 2021-08-04 19:17 UTC
JdbcOAuth2AuthorizationService persists the tokens as Blobs (authorization_code_value, oidc_id_token_value, refresh_token_value and authorization_code_value). 

It works great with H2 but I'm not sure if it works with Postgres (my case) or even another database. 
Other point, it's harder to query the database directly, for maintenence or debugging. I'm not sure about performance.

All above fields can be easily represented as Strings, so my sugestion is to change the sql types to Varchar instead of Blob. 

BTW, maybe there is a good reason to use Blobs but I can't see.

**Comment by jgrandja** [comment] 2021-08-09 14:54
@clgraf We've aligned `JdbcOAuth2AuthorizationService` with [JdbcOAuth2AuthorizedClientService](https://github.com/spring-projects/spring-security/blob/006b9b960797d279b31cf8c8d16f1549c5632b2c/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/JdbcOAuth2AuthorizedClientService.java#L70) (in `spring-security-oauth2-client`) as they both use `blob` for storing token credentials.

If you want to use `varchar` instead, you may customize the configuration. See this [comment](https://github.com/spring-projects-experimental/spring-authorization-server/issues/347#issuecomment-882894833) for further details.

Closing this as a duplicate of gh-347.

**Closed by jgrandja** 2021-08-09 14:54 UTC
Labels: type: bug
