### ISSUE TITLE
Where I can get a worked demo? Now except master branch, other (0.0.1/0.0.2/0.0.3) i all get errors

### ISSUE THREAD

**Issue by BestLalaVm** [spring-projects-experimental/spring-authorization-server#195] opened 2021-01-16 03:15 UTC
error such as:
 Could not resolve all dependencies for configuration ':spring-security-oauth2-authorization-server-docs-manual:te
stCompile'.
   > Did not resolve 'org.mockito:mockito-core:3.6.0' which has been forced / substituted to a different version: '
3.7.0'
   > Did not resolve 'org.assertj:assertj-core:3.18.0' which has been forced / substituted to a different version:
'3.18.1'
   > Did not resolve 'org.springframework:spring-test:5.3.0' which has been forced / substituted to a different ver
sion: '5.3.3'
   > Did not resolve 'org.springframework:spring-core:5.3.0' which has been forced / substituted to a different ver
sion: '5.3.3'
   > Did not resolve 'org.springframework:spring-jcl:5.3.0' which has been forced / substituted to a different vers
ion: '5.3.3'

**Comment by jgrandja** [comment] 2021-01-18 19:29
@BestLalaVm Please do not double post the same issue. I'll close this as duplicate of #194

**Closed by jgrandja** 2021-01-18 19:29 UTC
Labels: type: bug
