### ISSUE TITLE
Can 'UserConsentPage.displayConsent' support front-end separation?

### ISSUE THREAD

**Issue by houkunlin** [spring-projects-experimental/spring-authorization-server#136] opened 2020-10-20 09:05 UTC
https://github.com/spring-projects-experimental/spring-authorization-server/blob/aa5133e170472aee88cde6d0be6608c7035cfb5a/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/web/OAuth2AuthorizationEndpointFilter.java#L606

UserConsentPage.displayConsent 能否支持前后端分离？不直接输出html文档，而是重定向到指定前端URL，然后前端向后端Get请求授权信息，用户同意后前端构建post请求后端申请同意，这样可以自定义授权请求页面。

Can UserConsentPage.displayConsent support front-end and back-end separation? Instead of outputting the html document directly, it redirects to the specified front-end URL, and then the front-end requests authorization information from the back-end Get. After the user agrees, the front-end constructs a post to request the back-end to apply for consent, so that the authorization request page can be customized.

![VISIO_931_8DSXS0cgx9-2020-10-20 17_23_56](https://user-images.githubusercontent.com/12333292/96567165-13023300-12f9-11eb-95cb-31e767698e3d.png)

来自谷歌翻译/From Google Translate

**Comment by jgrandja** [comment] 2020-10-23 18:54
@houkunlin We do plan on providing a number of customizable configuration options, including a custom User Consent page. 

However, this will come at a later point after we have implemented enough features to qualify for a candidate MVP and especially after we are confident the public API's are stable enough. There is still a lot more work to do before we "open" things up to allow for custom configuration.

I'm going to close this as a duplicate of #139 as it will capture all the possible configuration options.

**Closed by jgrandja** 2020-10-23 18:54 UTC
Labels: status: waiting-for-triage
