### ISSUE TITLE
Refresh token should not be issued if client is not configured with refresh_token grant type

### ISSUE THREAD

**Issue by lspil** [spring-projects-experimental/spring-authorization-server#155] opened 2020-11-15 11:12 UTC
This behavior is strange from my point of view. If I enable the refresh token

.tokenSettings(t -> {
          t.enableRefreshTokens(true);
 })

Which is also the default out of my observations. Even if the client doesn't support the REFRESH_TOKEN grant type, I get a refresh token in the response. Now, of course, I can never use that value because the client doesn't support this grant type. So why do I need to get the value at all then?

Maybe it's just my opinion, but I find this behavior strange. Shouldn't these two configurations be somehow coordinated?

**Comment by lspil** [comment] 2020-11-15 11:13
I forgot to mention I reproduce this in version 0.0.3

**Comment by jgrandja** [comment] 2020-11-16 16:03
Good catch @lspil. Would you be interested in submitting a fix for this?

**Comment by lspil** [comment] 2020-11-22 09:11
Hi. Sorry for the late answer. If nobody took it yet, yes. I could. Let me know if you assign it to me. Thanks :)

**Comment by jgrandja** [comment] 2020-11-23 14:30
Thanks @lspil. The issue is yours!

**Closed** 2020-12-08 19:19 UTC
Labels: type: bug
