### ISSUE TITLE
OAuth2Authorization Or OAuth2AuthorizationService ORM Simple Convert ?

### ISSUE THREAD

**Issue by lanmingle** [spring-projects-experimental/spring-authorization-server#214] opened 2021-02-05 09:42 UTC
OAuth2AuthorizationService和OAuth2Authorization如何实现JDBC或MongoDB转换？结构有些复杂。

translation：

How do OAuth2AuthorizationService and OAuth2Authorization implement JDBC or MongoDB conversion? The structure is somewhat complicated.

see: OAuth2Tokens.tokens ， AbstractOAuth2Token multiple implementation , simplify ?

**Comment by lanmingle** [comment] 2021-02-09 04:17
close by #213

**Comment by lanmingle** [comment] 2021-02-25 06:51
还是太复杂了！

OAuth2Authorization.tokens 和 OAuth2Authorization.attributes 无法简单地进行转换。

OAuth2Authorization.attributes 应独立对象，不与OAuth2Authorization 直接关联，可以提供外部存储，如 redis 等。

另外是否改进 OAuth2AuthorizationService.findByToken 变得使用容易。

---

It's still too complicated!

OAuth2Authorization.tokens and OAuth2Authorization.attributes cannot be easily converted.

OAuth2Authorization.attributes should be an independent object, not directly associated with OAuth2Authorization, and can provide external storage, such as redis.

In addition, whether to improve OAuth2AuthorizationService.findByToken becomes easier to use.

**Comment by lanmingle** [comment] 2021-02-25 06:54
eg(RegisteredClient):

``` java


/**
 * @see org.springframework.security.oauth2.core.ClientAuthenticationMethod
 * @see org.springframework.security.oauth2.core.AuthorizationGrantType
 * @see org.springframework.security.oauth2.server.authorization.config.ClientSettings
 * @see org.springframework.security.oauth2.server.authorization.config.TokenSettings
 * @see org.springframework.security.oauth2.server.authorization.client.RegisteredClient
 */
@Getter
@Setter
@ToString
@EqualsAndHashCode(of = {"id"})
@Document(collection = "OidcRegisteredClient")
@CompoundIndexes({
        @CompoundIndex(def = "{'clientId': 1}", unique = true)
})
public class OidcRegisteredClient {

    @Id
    private String id;

    private String clientId;

    private String clientSecret;

    private Set<OidcClientAuthenticationMethod> clientAuthenticationMethods;

    private Set<OidcAuthorizationGrantType> authorizationGrantTypes;

    private Set<String> redirectUris;

    private Set<String> scopes;

    private Set<OidcClientSettings> clientSettings;

    private Set<OidcTokenSettings> tokenSettings;

}

// ... 其它

@Slf4j
@Repository
public class DelegateRegisteredClientRepository implements RegisteredClientRepository {

    @Autowired
    private OidcRegisteredClientService registeredClientService;

    @Autowired
    private RegisteredClientConverter registeredClientConverter;

    @Override
    public RegisteredClient findById(String id) {
        return this.registeredClientService.getById(id).map(registeredClient -> this.registeredClientConverter.convert(registeredClient)).orElse(null);
    }

    @Override
    public RegisteredClient findByClientId(String clientId) {
        return this.registeredClientService.getByClientId(clientId).map(registeredClient -> this.registeredClientConverter.convert(registeredClient)).orElse(null);
    }

}

```

**Comment by jgrandja** [comment] 2021-02-25 19:32
@lanmingle I logged a new ticket that will provide a JDBC implementation.

I'll close this as a duplicate of #245

**Closed by jgrandja** 2021-02-25 19:32 UTC
Labels: status: waiting-for-triage
